apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bitrise-api
  annotations:
    github.com/project-slug: Staffbase/bitrise-api
  tags:
    - makefile
spec:
  type: service
  lifecycle: production
