// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CustomBitriseYmlModelApp custom bitrise yml model app
//
// swagger:model customBitriseYmlModelApp
type CustomBitriseYmlModelApp struct {

	// Environment variables for the application workflows, e.g. {"env1":"val1","env2":"val2"}
	Envs map[string]string `json:"envs,omitempty"`
}

// Validate validates this custom bitrise yml model app
func (m *CustomBitriseYmlModelApp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this custom bitrise yml model app based on context it is used
func (m *CustomBitriseYmlModelApp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomBitriseYmlModelApp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomBitriseYmlModelApp) UnmarshalBinary(b []byte) error {
	var res CustomBitriseYmlModelApp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
