// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ServiceDtoGroup service dto group
//
// swagger:model service.dto.Group
type ServiceDtoGroup struct {

	// name
	Name string `json:"name,omitempty"`

	// slug
	Slug string `json:"slug,omitempty"`
}

// Validate validates this service dto group
func (m *ServiceDtoGroup) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service dto group based on context it is used
func (m *ServiceDtoGroup) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceDtoGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceDtoGroup) UnmarshalBinary(b []byte) error {
	var res ServiceDtoGroup
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
