// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ServiceDtoValidateBitriseYMLRespModel service dto validate bitrise y m l resp model
//
// swagger:model service.dto.ValidateBitriseYMLRespModel
type ServiceDtoValidateBitriseYMLRespModel struct {

	// Validation errors
	Errors []string `json:"errors"`

	// Validation warnings
	Warnings []string `json:"warnings"`
}

// Validate validates this service dto validate bitrise y m l resp model
func (m *ServiceDtoValidateBitriseYMLRespModel) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service dto validate bitrise y m l resp model based on context it is used
func (m *ServiceDtoValidateBitriseYMLRespModel) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceDtoValidateBitriseYMLRespModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceDtoValidateBitriseYMLRespModel) UnmarshalBinary(b []byte) error {
	var res ServiceDtoValidateBitriseYMLRespModel
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
