// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V0AppNotificationSettingsParams v0 app notification settings params
//
// swagger:model v0.AppNotificationSettingsParams
type V0AppNotificationSettingsParams struct {

	// When should Bitrise send notifications for the users on build failure? Possible values: always, never, change
	OnFailure string `json:"on_failure,omitempty"`

	// When should Bitrise send notifications for the users on build success? Possible values: always, never, change
	OnSuccess string `json:"on_success,omitempty"`
}

// Validate validates this v0 app notification settings params
func (m *V0AppNotificationSettingsParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v0 app notification settings params based on context it is used
func (m *V0AppNotificationSettingsParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0AppNotificationSettingsParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0AppNotificationSettingsParams) UnmarshalBinary(b []byte) error {
	var res V0AppNotificationSettingsParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
