// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// V0ArchivedBuildArtifact v0 archived build artifact
//
// swagger:model v0.ArchivedBuildArtifact
type V0ArchivedBuildArtifact struct {

	// artifact meta
	ArtifactMeta any `json:"artifact_meta,omitempty"`

	// artifact type
	ArtifactType string `json:"artifact_type,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// file size bytes
	FileSizeBytes int64 `json:"file_size_bytes,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// is public page enabled
	IsPublicPageEnabled bool `json:"is_public_page_enabled,omitempty"`

	// public page token
	PublicPageToken string `json:"public_page_token,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this v0 archived build artifact
func (m *V0ArchivedBuildArtifact) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v0 archived build artifact based on context it is used
func (m *V0ArchivedBuildArtifact) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0ArchivedBuildArtifact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0ArchivedBuildArtifact) UnmarshalBinary(b []byte) error {
	var res V0ArchivedBuildArtifact
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
