// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V0AvatarPromoteResponseItemModel v0 avatar promote response item model
//
// swagger:model v0.AvatarPromoteResponseItemModel
type V0AvatarPromoteResponseItemModel struct {

	// is candidate
	IsCandidate bool `json:"is_candidate,omitempty"`

	// slug
	Slug string `json:"slug,omitempty"`

	// upload file name
	UploadFileName string `json:"upload_file_name,omitempty"`

	// upload file size
	UploadFileSize int64 `json:"upload_file_size,omitempty"`
}

// Validate validates this v0 avatar promote response item model
func (m *V0AvatarPromoteResponseItemModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v0 avatar promote response item model based on context it is used
func (m *V0AvatarPromoteResponseItemModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0AvatarPromoteResponseItemModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0AvatarPromoteResponseItemModel) UnmarshalBinary(b []byte) error {
	var res V0AvatarPromoteResponseItemModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
