// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// V0AppRespModel v0 app resp model
//
// swagger:model v0.AppRespModel
type V0AppRespModel struct {

	// slug
	Slug string `json:"slug,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this v0 app resp model
func (m *V0AppRespModel) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v0 app resp model based on context it is used
func (m *V0AppRespModel) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0AppRespModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0AppRespModel) UnmarshalBinary(b []byte) error {
	var res V0AppRespModel
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
