// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V0ArchivedBuildResponseItemModel v0 archived build response item model
//
// swagger:model v0.ArchivedBuildResponseItemModel
type V0ArchivedBuildResponseItemModel struct {

	// abort reason
	AbortReason string `json:"abort_reason,omitempty"`

	// branch
	Branch string `json:"branch,omitempty"`

	// build artifacts
	BuildArtifacts []*V0ArchivedBuildArtifact `json:"build_artifacts"`

	// build number
	BuildNumber int64 `json:"build_number,omitempty"`

	// commit hash
	CommitHash string `json:"commit_hash,omitempty"`

	// commit message
	CommitMessage string `json:"commit_message,omitempty"`

	// credit cost
	CreditCost int64 `json:"credit_cost,omitempty"`

	// finished at
	FinishedAt string `json:"finished_at,omitempty"`

	// machine type id
	MachineTypeID string `json:"machine_type_id,omitempty"`

	// original build params
	OriginalBuildParams []int64 `json:"original_build_params"`

	// pipeline workflow id
	PipelineWorkflowID string `json:"pipeline_workflow_id,omitempty"`

	// pull request id
	PullRequestID int64 `json:"pull_request_id,omitempty"`

	// pull request target branch
	PullRequestTargetBranch string `json:"pull_request_target_branch,omitempty"`

	// pull request view url
	PullRequestViewURL string `json:"pull_request_view_url,omitempty"`

	// slug
	Slug string `json:"slug,omitempty"`

	// stack identifier
	StackIdentifier string `json:"stack_identifier,omitempty"`

	// started on worker at
	StartedOnWorkerAt string `json:"started_on_worker_at,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`

	// status text
	StatusText string `json:"status_text,omitempty"`

	// tag
	Tag string `json:"tag,omitempty"`

	// triggered by
	TriggeredBy string `json:"triggered_by,omitempty"`

	// triggered workflow
	TriggeredWorkflow string `json:"triggered_workflow,omitempty"`
}

// Validate validates this v0 archived build response item model
func (m *V0ArchivedBuildResponseItemModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuildArtifacts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V0ArchivedBuildResponseItemModel) validateBuildArtifacts(formats strfmt.Registry) error {
	if swag.IsZero(m.BuildArtifacts) { // not required
		return nil
	}

	for i := 0; i < len(m.BuildArtifacts); i++ {
		if swag.IsZero(m.BuildArtifacts[i]) { // not required
			continue
		}

		if m.BuildArtifacts[i] != nil {
			if err := m.BuildArtifacts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("build_artifacts" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("build_artifacts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v0 archived build response item model based on the context it is used
func (m *V0ArchivedBuildResponseItemModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBuildArtifacts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V0ArchivedBuildResponseItemModel) contextValidateBuildArtifacts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.BuildArtifacts); i++ {

		if m.BuildArtifacts[i] != nil {
			if err := m.BuildArtifacts[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("build_artifacts" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("build_artifacts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V0ArchivedBuildResponseItemModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0ArchivedBuildResponseItemModel) UnmarshalBinary(b []byte) error {
	var res V0ArchivedBuildResponseItemModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
