// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// V0BuildCertificateContentModel v0 build certificate content model
//
// swagger:model v0.BuildCertificateContentModel
type V0BuildCertificateContentModel struct {

	// Read-only. This certificate's notAfter date in RFC 3339 / ISO 8601 (UTC). Computed server-side once the file is processed; null when it could not be extracted from the certificate.
	// Example: 2027-05-28T00:00:00Z
	// Read Only: true
	// Format: date-time
	ExpiryDate strfmt.DateTime `json:"expiry_date,omitempty"`

	// Read-only. X.509 serial number of this certificate, rendered as uppercase hexadecimal. Computed server-side once the file is processed; null when it could not be extracted from the certificate.
	// Example: A1B2C3D4E5F60718
	// Read Only: true
	Serial string `json:"serial,omitempty"`
}

// Validate validates this v0 build certificate content model
func (m *V0BuildCertificateContentModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiryDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V0BuildCertificateContentModel) validateExpiryDate(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExpiryDate) { // not required
		return nil
	}

	if err := validate.FormatOf("expiry_date", "body", "date-time", m.ExpiryDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this v0 build certificate content model based on the context it is used
func (m *V0BuildCertificateContentModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExpiryDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSerial(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V0BuildCertificateContentModel) contextValidateExpiryDate(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "expiry_date", "body", m.ExpiryDate); err != nil {
		return err
	}

	return nil
}

func (m *V0BuildCertificateContentModel) contextValidateSerial(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "serial", "body", m.Serial); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V0BuildCertificateContentModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0BuildCertificateContentModel) UnmarshalBinary(b []byte) error {
	var res V0BuildCertificateContentModel
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
