// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// V0BuildWorkflowListResponseModel v0 build workflow list response model
//
// swagger:model v0.BuildWorkflowListResponseModel
type V0BuildWorkflowListResponseModel struct {

	// data
	Data []string `json:"data"`
}

// Validate validates this v0 build workflow list response model
func (m *V0BuildWorkflowListResponseModel) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v0 build workflow list response model based on context it is used
func (m *V0BuildWorkflowListResponseModel) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0BuildWorkflowListResponseModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0BuildWorkflowListResponseModel) UnmarshalBinary(b []byte) error {
	var res V0BuildWorkflowListResponseModel
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
