// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V0CacheItemListResponseItemModel v0 cache item list response item model
//
// swagger:model v0.CacheItemListResponseItemModel
type V0CacheItemListResponseItemModel struct {

	// app id
	AppID string `json:"app_id,omitempty"`

	// archive filename
	ArchiveFilename string `json:"archive_filename,omitempty"`

	// archive size
	ArchiveSize int64 `json:"archive_size,omitempty"`

	// cache key
	CacheKey string `json:"cache_key,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// expires at
	ExpiresAt string `json:"expires_at,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// last used at
	LastUsedAt string `json:"last_used_at,omitempty"`
}

// Validate validates this v0 cache item list response item model
func (m *V0CacheItemListResponseItemModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v0 cache item list response item model based on context it is used
func (m *V0CacheItemListResponseItemModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0CacheItemListResponseItemModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0CacheItemListResponseItemModel) UnmarshalBinary(b []byte) error {
	var res V0CacheItemListResponseItemModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
