// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V0OrganizationUpdateMachineTypeParams v0 organization update machine type params
//
// swagger:model v0.OrganizationUpdateMachineTypeParams
type V0OrganizationUpdateMachineTypeParams struct {

	// Machine type to migrate from
	FromMachine string `json:"from_machine,omitempty"`

	// Machine type to migrate to
	ToMachine string `json:"to_machine,omitempty"`
}

// Validate validates this v0 organization update machine type params
func (m *V0OrganizationUpdateMachineTypeParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v0 organization update machine type params based on context it is used
func (m *V0OrganizationUpdateMachineTypeParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0OrganizationUpdateMachineTypeParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0OrganizationUpdateMachineTypeParams) UnmarshalBinary(b []byte) error {
	var res V0OrganizationUpdateMachineTypeParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
