// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// V0OrganizationGoogleServiceCredentialResponseItem v0 organization google service credential response item
//
// swagger:model v0.OrganizationGoogleServiceCredentialResponseItem
type V0OrganizationGoogleServiceCredentialResponseItem struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// is enterprise account
	IsEnterpriseAccount bool `json:"is_enterprise_account,omitempty"`

	// issuer id
	IssuerID string `json:"issuer_id,omitempty"`

	// key id
	KeyID string `json:"key_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// slug
	Slug string `json:"slug,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this v0 organization google service credential response item
func (m *V0OrganizationGoogleServiceCredentialResponseItem) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v0 organization google service credential response item based on context it is used
func (m *V0OrganizationGoogleServiceCredentialResponseItem) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V0OrganizationGoogleServiceCredentialResponseItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V0OrganizationGoogleServiceCredentialResponseItem) UnmarshalBinary(b []byte) error {
	var res V0OrganizationGoogleServiceCredentialResponseItem
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
