// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAndroidKeystoreFileDeleteParams creates a new AndroidKeystoreFileDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAndroidKeystoreFileDeleteParams() *AndroidKeystoreFileDeleteParams {
	return &AndroidKeystoreFileDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAndroidKeystoreFileDeleteParamsWithTimeout creates a new AndroidKeystoreFileDeleteParams object
// with the ability to set a timeout on a request.
func NewAndroidKeystoreFileDeleteParamsWithTimeout(timeout time.Duration) *AndroidKeystoreFileDeleteParams {
	return &AndroidKeystoreFileDeleteParams{
		timeout: timeout,
	}
}

// NewAndroidKeystoreFileDeleteParamsWithContext creates a new AndroidKeystoreFileDeleteParams object
// with the ability to set a context for a request.
func NewAndroidKeystoreFileDeleteParamsWithContext(ctx context.Context) *AndroidKeystoreFileDeleteParams {
	return &AndroidKeystoreFileDeleteParams{
		Context: ctx,
	}
}

// NewAndroidKeystoreFileDeleteParamsWithHTTPClient creates a new AndroidKeystoreFileDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewAndroidKeystoreFileDeleteParamsWithHTTPClient(client *http.Client) *AndroidKeystoreFileDeleteParams {
	return &AndroidKeystoreFileDeleteParams{
		HTTPClient: client,
	}
}

/*
AndroidKeystoreFileDeleteParams contains all the parameters to send to the API endpoint

	for the android keystore file delete operation.

	Typically these are written to a http.Request.
*/
type AndroidKeystoreFileDeleteParams struct {

	/* AndroidKeystoreFileSlug.

	   Android keystore file slug
	*/
	AndroidKeystoreFileSlug string

	/* AppSlug.

	   App slug
	*/
	AppSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the android keystore file delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AndroidKeystoreFileDeleteParams) WithDefaults() *AndroidKeystoreFileDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the android keystore file delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AndroidKeystoreFileDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the android keystore file delete params
func (o *AndroidKeystoreFileDeleteParams) WithTimeout(timeout time.Duration) *AndroidKeystoreFileDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the android keystore file delete params
func (o *AndroidKeystoreFileDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the android keystore file delete params
func (o *AndroidKeystoreFileDeleteParams) WithContext(ctx context.Context) *AndroidKeystoreFileDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the android keystore file delete params
func (o *AndroidKeystoreFileDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the android keystore file delete params
func (o *AndroidKeystoreFileDeleteParams) WithHTTPClient(client *http.Client) *AndroidKeystoreFileDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the android keystore file delete params
func (o *AndroidKeystoreFileDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAndroidKeystoreFileSlug adds the androidKeystoreFileSlug to the android keystore file delete params
func (o *AndroidKeystoreFileDeleteParams) WithAndroidKeystoreFileSlug(androidKeystoreFileSlug string) *AndroidKeystoreFileDeleteParams {
	o.SetAndroidKeystoreFileSlug(androidKeystoreFileSlug)
	return o
}

// SetAndroidKeystoreFileSlug adds the androidKeystoreFileSlug to the android keystore file delete params
func (o *AndroidKeystoreFileDeleteParams) SetAndroidKeystoreFileSlug(androidKeystoreFileSlug string) {
	o.AndroidKeystoreFileSlug = androidKeystoreFileSlug
}

// WithAppSlug adds the appSlug to the android keystore file delete params
func (o *AndroidKeystoreFileDeleteParams) WithAppSlug(appSlug string) *AndroidKeystoreFileDeleteParams {
	o.SetAppSlug(appSlug)
	return o
}

// SetAppSlug adds the appSlug to the android keystore file delete params
func (o *AndroidKeystoreFileDeleteParams) SetAppSlug(appSlug string) {
	o.AppSlug = appSlug
}

// WriteToRequest writes these params to a swagger request
func (o *AndroidKeystoreFileDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param android-keystore-file-slug
	if err := r.SetPathParam("android-keystore-file-slug", o.AndroidKeystoreFileSlug); err != nil {
		return err
	}

	// path param app-slug
	if err := r.SetPathParam("app-slug", o.AppSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
