// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/Staffbase/bitrise-api/go/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// AppChangeLinkedRepositoriesReader is a Reader for the AppChangeLinkedRepositories structure.
type AppChangeLinkedRepositoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AppChangeLinkedRepositoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewAppChangeLinkedRepositoriesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAppChangeLinkedRepositoriesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAppChangeLinkedRepositoriesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAppChangeLinkedRepositoriesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /apps/{app-slug}/github-app-connection-configuration/update-linked-repositories] app-change-linked-repositories", response, response.Code())
	}
}

// NewAppChangeLinkedRepositoriesNoContent creates a AppChangeLinkedRepositoriesNoContent with default headers values
func NewAppChangeLinkedRepositoriesNoContent() *AppChangeLinkedRepositoriesNoContent {
	return &AppChangeLinkedRepositoriesNoContent{}
}

// AppChangeLinkedRepositoriesNoContent describes a response with status code 204, with default header values.
//
// No Content
type AppChangeLinkedRepositoriesNoContent struct {
}

// IsSuccess returns true when this app change linked repositories no content response has a 2xx status code
func (o *AppChangeLinkedRepositoriesNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this app change linked repositories no content response has a 3xx status code
func (o *AppChangeLinkedRepositoriesNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this app change linked repositories no content response has a 4xx status code
func (o *AppChangeLinkedRepositoriesNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this app change linked repositories no content response has a 5xx status code
func (o *AppChangeLinkedRepositoriesNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this app change linked repositories no content response a status code equal to that given
func (o *AppChangeLinkedRepositoriesNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the app change linked repositories no content response
func (o *AppChangeLinkedRepositoriesNoContent) Code() int {
	return 204
}

func (o *AppChangeLinkedRepositoriesNoContent) Error() string {
	return fmt.Sprintf("[POST /apps/{app-slug}/github-app-connection-configuration/update-linked-repositories][%d] appChangeLinkedRepositoriesNoContent", 204)
}

func (o *AppChangeLinkedRepositoriesNoContent) String() string {
	return fmt.Sprintf("[POST /apps/{app-slug}/github-app-connection-configuration/update-linked-repositories][%d] appChangeLinkedRepositoriesNoContent", 204)
}

func (o *AppChangeLinkedRepositoriesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAppChangeLinkedRepositoriesUnauthorized creates a AppChangeLinkedRepositoriesUnauthorized with default headers values
func NewAppChangeLinkedRepositoriesUnauthorized() *AppChangeLinkedRepositoriesUnauthorized {
	return &AppChangeLinkedRepositoriesUnauthorized{}
}

// AppChangeLinkedRepositoriesUnauthorized describes a response with status code 401, with default header values.
//
// Unauthorized
type AppChangeLinkedRepositoriesUnauthorized struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this app change linked repositories unauthorized response has a 2xx status code
func (o *AppChangeLinkedRepositoriesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this app change linked repositories unauthorized response has a 3xx status code
func (o *AppChangeLinkedRepositoriesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this app change linked repositories unauthorized response has a 4xx status code
func (o *AppChangeLinkedRepositoriesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this app change linked repositories unauthorized response has a 5xx status code
func (o *AppChangeLinkedRepositoriesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this app change linked repositories unauthorized response a status code equal to that given
func (o *AppChangeLinkedRepositoriesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the app change linked repositories unauthorized response
func (o *AppChangeLinkedRepositoriesUnauthorized) Code() int {
	return 401
}

func (o *AppChangeLinkedRepositoriesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apps/{app-slug}/github-app-connection-configuration/update-linked-repositories][%d] appChangeLinkedRepositoriesUnauthorized %s", 401, payload)
}

func (o *AppChangeLinkedRepositoriesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apps/{app-slug}/github-app-connection-configuration/update-linked-repositories][%d] appChangeLinkedRepositoriesUnauthorized %s", 401, payload)
}

func (o *AppChangeLinkedRepositoriesUnauthorized) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AppChangeLinkedRepositoriesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAppChangeLinkedRepositoriesForbidden creates a AppChangeLinkedRepositoriesForbidden with default headers values
func NewAppChangeLinkedRepositoriesForbidden() *AppChangeLinkedRepositoriesForbidden {
	return &AppChangeLinkedRepositoriesForbidden{}
}

// AppChangeLinkedRepositoriesForbidden describes a response with status code 403, with default header values.
//
// Forbidden
type AppChangeLinkedRepositoriesForbidden struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this app change linked repositories forbidden response has a 2xx status code
func (o *AppChangeLinkedRepositoriesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this app change linked repositories forbidden response has a 3xx status code
func (o *AppChangeLinkedRepositoriesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this app change linked repositories forbidden response has a 4xx status code
func (o *AppChangeLinkedRepositoriesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this app change linked repositories forbidden response has a 5xx status code
func (o *AppChangeLinkedRepositoriesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this app change linked repositories forbidden response a status code equal to that given
func (o *AppChangeLinkedRepositoriesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the app change linked repositories forbidden response
func (o *AppChangeLinkedRepositoriesForbidden) Code() int {
	return 403
}

func (o *AppChangeLinkedRepositoriesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apps/{app-slug}/github-app-connection-configuration/update-linked-repositories][%d] appChangeLinkedRepositoriesForbidden %s", 403, payload)
}

func (o *AppChangeLinkedRepositoriesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apps/{app-slug}/github-app-connection-configuration/update-linked-repositories][%d] appChangeLinkedRepositoriesForbidden %s", 403, payload)
}

func (o *AppChangeLinkedRepositoriesForbidden) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AppChangeLinkedRepositoriesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAppChangeLinkedRepositoriesNotFound creates a AppChangeLinkedRepositoriesNotFound with default headers values
func NewAppChangeLinkedRepositoriesNotFound() *AppChangeLinkedRepositoriesNotFound {
	return &AppChangeLinkedRepositoriesNotFound{}
}

// AppChangeLinkedRepositoriesNotFound describes a response with status code 404, with default header values.
//
// Not found
type AppChangeLinkedRepositoriesNotFound struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this app change linked repositories not found response has a 2xx status code
func (o *AppChangeLinkedRepositoriesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this app change linked repositories not found response has a 3xx status code
func (o *AppChangeLinkedRepositoriesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this app change linked repositories not found response has a 4xx status code
func (o *AppChangeLinkedRepositoriesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this app change linked repositories not found response has a 5xx status code
func (o *AppChangeLinkedRepositoriesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this app change linked repositories not found response a status code equal to that given
func (o *AppChangeLinkedRepositoriesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the app change linked repositories not found response
func (o *AppChangeLinkedRepositoriesNotFound) Code() int {
	return 404
}

func (o *AppChangeLinkedRepositoriesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apps/{app-slug}/github-app-connection-configuration/update-linked-repositories][%d] appChangeLinkedRepositoriesNotFound %s", 404, payload)
}

func (o *AppChangeLinkedRepositoriesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /apps/{app-slug}/github-app-connection-configuration/update-linked-repositories][%d] appChangeLinkedRepositoriesNotFound %s", 404, payload)
}

func (o *AppChangeLinkedRepositoriesNotFound) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AppChangeLinkedRepositoriesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// AppChangeLinkedRepositoriesBody app change linked repositories body
//
// swagger:model AppChangeLinkedRepositoriesBody
type AppChangeLinkedRepositoriesBody struct {

	// List of repository full names (org/repo) to be linked
	Repositories []string `json:"repositories"`

	// unlimited repo access
	UnlimitedRepoAccess bool `json:"unlimited_repo_access,omitempty"`
}

// Validate validates this app change linked repositories body
func (o *AppChangeLinkedRepositoriesBody) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app change linked repositories body based on context it is used
func (o *AppChangeLinkedRepositoriesBody) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AppChangeLinkedRepositoriesBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AppChangeLinkedRepositoriesBody) UnmarshalBinary(b []byte) error {
	var res AppChangeLinkedRepositoriesBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
