// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Staffbase/bitrise-api/go/models"
)

// AppRolesUpdateReader is a Reader for the AppRolesUpdate structure.
type AppRolesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AppRolesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAppRolesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewAppRolesUpdateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /apps/{app-slug}/roles/{role-name}] app-roles-update", response, response.Code())
	}
}

// NewAppRolesUpdateOK creates a AppRolesUpdateOK with default headers values
func NewAppRolesUpdateOK() *AppRolesUpdateOK {
	return &AppRolesUpdateOK{}
}

/*
AppRolesUpdateOK describes a response with status code 200, with default header values.

List of group slugs
*/
type AppRolesUpdateOK struct {
	Payload *models.AppRolesUpdateOKBody
}

// IsSuccess returns true when this app roles update o k response has a 2xx status code
func (o *AppRolesUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this app roles update o k response has a 3xx status code
func (o *AppRolesUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this app roles update o k response has a 4xx status code
func (o *AppRolesUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this app roles update o k response has a 5xx status code
func (o *AppRolesUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this app roles update o k response a status code equal to that given
func (o *AppRolesUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the app roles update o k response
func (o *AppRolesUpdateOK) Code() int {
	return 200
}

func (o *AppRolesUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/roles/{role-name}][%d] appRolesUpdateOK  %+v", 200, o.Payload)
}

func (o *AppRolesUpdateOK) String() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/roles/{role-name}][%d] appRolesUpdateOK  %+v", 200, o.Payload)
}

func (o *AppRolesUpdateOK) GetPayload() *models.AppRolesUpdateOKBody {
	return o.Payload
}

func (o *AppRolesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppRolesUpdateOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppRolesUpdateUnprocessableEntity creates a AppRolesUpdateUnprocessableEntity with default headers values
func NewAppRolesUpdateUnprocessableEntity() *AppRolesUpdateUnprocessableEntity {
	return &AppRolesUpdateUnprocessableEntity{}
}

/*
AppRolesUpdateUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type AppRolesUpdateUnprocessableEntity struct {
	Payload *models.ServiceProxyErrorRespModel
}

// IsSuccess returns true when this app roles update unprocessable entity response has a 2xx status code
func (o *AppRolesUpdateUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this app roles update unprocessable entity response has a 3xx status code
func (o *AppRolesUpdateUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this app roles update unprocessable entity response has a 4xx status code
func (o *AppRolesUpdateUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this app roles update unprocessable entity response has a 5xx status code
func (o *AppRolesUpdateUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this app roles update unprocessable entity response a status code equal to that given
func (o *AppRolesUpdateUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the app roles update unprocessable entity response
func (o *AppRolesUpdateUnprocessableEntity) Code() int {
	return 422
}

func (o *AppRolesUpdateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/roles/{role-name}][%d] appRolesUpdateUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *AppRolesUpdateUnprocessableEntity) String() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/roles/{role-name}][%d] appRolesUpdateUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *AppRolesUpdateUnprocessableEntity) GetPayload() *models.ServiceProxyErrorRespModel {
	return o.Payload
}

func (o *AppRolesUpdateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceProxyErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
