// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Staffbase/bitrise-api/go/models"
)

// AppleAPICredentialListReader is a Reader for the AppleAPICredentialList structure.
type AppleAPICredentialListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AppleAPICredentialListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAppleAPICredentialListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAppleAPICredentialListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAppleAPICredentialListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAppleAPICredentialListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAppleAPICredentialListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAppleAPICredentialListOK creates a AppleAPICredentialListOK with default headers values
func NewAppleAPICredentialListOK() *AppleAPICredentialListOK {
	return &AppleAPICredentialListOK{}
}

/* AppleAPICredentialListOK describes a response with status code 200, with default header values.

OK
*/
type AppleAPICredentialListOK struct {
	Payload *models.V0AppleAPICredentialsListResponse
}

func (o *AppleAPICredentialListOK) Error() string {
	return fmt.Sprintf("[GET /users/{user-slug}/apple-api-credentials][%d] appleApiCredentialListOK  %+v", 200, o.Payload)
}
func (o *AppleAPICredentialListOK) GetPayload() *models.V0AppleAPICredentialsListResponse {
	return o.Payload
}

func (o *AppleAPICredentialListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V0AppleAPICredentialsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppleAPICredentialListBadRequest creates a AppleAPICredentialListBadRequest with default headers values
func NewAppleAPICredentialListBadRequest() *AppleAPICredentialListBadRequest {
	return &AppleAPICredentialListBadRequest{}
}

/* AppleAPICredentialListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type AppleAPICredentialListBadRequest struct {
	Payload *models.ServiceStandardErrorRespModel
}

func (o *AppleAPICredentialListBadRequest) Error() string {
	return fmt.Sprintf("[GET /users/{user-slug}/apple-api-credentials][%d] appleApiCredentialListBadRequest  %+v", 400, o.Payload)
}
func (o *AppleAPICredentialListBadRequest) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AppleAPICredentialListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppleAPICredentialListUnauthorized creates a AppleAPICredentialListUnauthorized with default headers values
func NewAppleAPICredentialListUnauthorized() *AppleAPICredentialListUnauthorized {
	return &AppleAPICredentialListUnauthorized{}
}

/* AppleAPICredentialListUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type AppleAPICredentialListUnauthorized struct {
	Payload *models.ServiceStandardErrorRespModel
}

func (o *AppleAPICredentialListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /users/{user-slug}/apple-api-credentials][%d] appleApiCredentialListUnauthorized  %+v", 401, o.Payload)
}
func (o *AppleAPICredentialListUnauthorized) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AppleAPICredentialListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppleAPICredentialListNotFound creates a AppleAPICredentialListNotFound with default headers values
func NewAppleAPICredentialListNotFound() *AppleAPICredentialListNotFound {
	return &AppleAPICredentialListNotFound{}
}

/* AppleAPICredentialListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type AppleAPICredentialListNotFound struct {
	Payload *models.ServiceStandardErrorRespModel
}

func (o *AppleAPICredentialListNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{user-slug}/apple-api-credentials][%d] appleApiCredentialListNotFound  %+v", 404, o.Payload)
}
func (o *AppleAPICredentialListNotFound) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AppleAPICredentialListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppleAPICredentialListInternalServerError creates a AppleAPICredentialListInternalServerError with default headers values
func NewAppleAPICredentialListInternalServerError() *AppleAPICredentialListInternalServerError {
	return &AppleAPICredentialListInternalServerError{}
}

/* AppleAPICredentialListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type AppleAPICredentialListInternalServerError struct {
	Payload *models.ServiceStandardErrorRespModel
}

func (o *AppleAPICredentialListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/{user-slug}/apple-api-credentials][%d] appleApiCredentialListInternalServerError  %+v", 500, o.Payload)
}
func (o *AppleAPICredentialListInternalServerError) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AppleAPICredentialListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
