// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAvailableStacksListParams creates a new AvailableStacksListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAvailableStacksListParams() *AvailableStacksListParams {
	return NewAvailableStacksListParamsWithTimeout(cr.DefaultTimeout)
}

// NewAvailableStacksListParamsWithTimeout creates a new AvailableStacksListParams object
// with the ability to set a timeout on a request.
func NewAvailableStacksListParamsWithTimeout(timeout time.Duration) *AvailableStacksListParams {
	return &AvailableStacksListParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewAvailableStacksListParamsWithContext creates a new AvailableStacksListParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [AvailableStacksListParams].
func NewAvailableStacksListParamsWithContext(ctx context.Context) *AvailableStacksListParams {
	return &AvailableStacksListParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewAvailableStacksListParamsWithHTTPClient creates a new AvailableStacksListParams object
// with the ability to set a custom HTTPClient for a request.
func NewAvailableStacksListParamsWithHTTPClient(client *http.Client) *AvailableStacksListParams {
	return &AvailableStacksListParams{
		HTTPClient: client,
	}
}

/*
AvailableStacksListParams contains all the parameters to send to the API endpoint

	for the available stacks list operation.

	Typically these are written to a http.Request.
*/
type AvailableStacksListParams struct {
	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the available stacks list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AvailableStacksListParams) WithDefaults() *AvailableStacksListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the available stacks list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AvailableStacksListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the available stacks list params.
func (o *AvailableStacksListParams) WithTimeout(timeout time.Duration) *AvailableStacksListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the available stacks list params.
func (o *AvailableStacksListParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the available stacks list params.
//
// Deprecated: use the operation call with context to pass the context instead of [AvailableStacksListParams].
func (o *AvailableStacksListParams) WithContext(ctx context.Context) *AvailableStacksListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the available stacks list params.
//
// Deprecated: use the operation call with context to pass the context instead of [AvailableStacksListParams].
func (o *AvailableStacksListParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the available stacks list params.
func (o *AvailableStacksListParams) WithHTTPClient(client *http.Client) *AvailableStacksListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the available stacks list params.
func (o *AvailableStacksListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *AvailableStacksListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
