// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Staffbase/bitrise-api/go/models"
)

// AvatarCandidateListReader is a Reader for the AvatarCandidateList structure.
type AvatarCandidateListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AvatarCandidateListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAvatarCandidateListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAvatarCandidateListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAvatarCandidateListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAvatarCandidateListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAvatarCandidateListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAvatarCandidateListOK creates a AvatarCandidateListOK with default headers values
func NewAvatarCandidateListOK() *AvatarCandidateListOK {
	return &AvatarCandidateListOK{}
}

/*
AvatarCandidateListOK describes a response with status code 200, with default header values.

OK
*/
type AvatarCandidateListOK struct {
	Payload *models.V0FindAvatarCandidateResponse
}

// IsSuccess returns true when this avatar candidate list o k response has a 2xx status code
func (o *AvatarCandidateListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this avatar candidate list o k response has a 3xx status code
func (o *AvatarCandidateListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this avatar candidate list o k response has a 4xx status code
func (o *AvatarCandidateListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this avatar candidate list o k response has a 5xx status code
func (o *AvatarCandidateListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this avatar candidate list o k response a status code equal to that given
func (o *AvatarCandidateListOK) IsCode(code int) bool {
	return code == 200
}

func (o *AvatarCandidateListOK) Error() string {
	return fmt.Sprintf("[GET /v0.1/apps/{app-slug}/avatar-candidates][%d] avatarCandidateListOK  %+v", 200, o.Payload)
}

func (o *AvatarCandidateListOK) String() string {
	return fmt.Sprintf("[GET /v0.1/apps/{app-slug}/avatar-candidates][%d] avatarCandidateListOK  %+v", 200, o.Payload)
}

func (o *AvatarCandidateListOK) GetPayload() *models.V0FindAvatarCandidateResponse {
	return o.Payload
}

func (o *AvatarCandidateListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V0FindAvatarCandidateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAvatarCandidateListBadRequest creates a AvatarCandidateListBadRequest with default headers values
func NewAvatarCandidateListBadRequest() *AvatarCandidateListBadRequest {
	return &AvatarCandidateListBadRequest{}
}

/*
AvatarCandidateListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type AvatarCandidateListBadRequest struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this avatar candidate list bad request response has a 2xx status code
func (o *AvatarCandidateListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this avatar candidate list bad request response has a 3xx status code
func (o *AvatarCandidateListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this avatar candidate list bad request response has a 4xx status code
func (o *AvatarCandidateListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this avatar candidate list bad request response has a 5xx status code
func (o *AvatarCandidateListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this avatar candidate list bad request response a status code equal to that given
func (o *AvatarCandidateListBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *AvatarCandidateListBadRequest) Error() string {
	return fmt.Sprintf("[GET /v0.1/apps/{app-slug}/avatar-candidates][%d] avatarCandidateListBadRequest  %+v", 400, o.Payload)
}

func (o *AvatarCandidateListBadRequest) String() string {
	return fmt.Sprintf("[GET /v0.1/apps/{app-slug}/avatar-candidates][%d] avatarCandidateListBadRequest  %+v", 400, o.Payload)
}

func (o *AvatarCandidateListBadRequest) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AvatarCandidateListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAvatarCandidateListUnauthorized creates a AvatarCandidateListUnauthorized with default headers values
func NewAvatarCandidateListUnauthorized() *AvatarCandidateListUnauthorized {
	return &AvatarCandidateListUnauthorized{}
}

/*
AvatarCandidateListUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type AvatarCandidateListUnauthorized struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this avatar candidate list unauthorized response has a 2xx status code
func (o *AvatarCandidateListUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this avatar candidate list unauthorized response has a 3xx status code
func (o *AvatarCandidateListUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this avatar candidate list unauthorized response has a 4xx status code
func (o *AvatarCandidateListUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this avatar candidate list unauthorized response has a 5xx status code
func (o *AvatarCandidateListUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this avatar candidate list unauthorized response a status code equal to that given
func (o *AvatarCandidateListUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *AvatarCandidateListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v0.1/apps/{app-slug}/avatar-candidates][%d] avatarCandidateListUnauthorized  %+v", 401, o.Payload)
}

func (o *AvatarCandidateListUnauthorized) String() string {
	return fmt.Sprintf("[GET /v0.1/apps/{app-slug}/avatar-candidates][%d] avatarCandidateListUnauthorized  %+v", 401, o.Payload)
}

func (o *AvatarCandidateListUnauthorized) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AvatarCandidateListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAvatarCandidateListNotFound creates a AvatarCandidateListNotFound with default headers values
func NewAvatarCandidateListNotFound() *AvatarCandidateListNotFound {
	return &AvatarCandidateListNotFound{}
}

/*
AvatarCandidateListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type AvatarCandidateListNotFound struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this avatar candidate list not found response has a 2xx status code
func (o *AvatarCandidateListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this avatar candidate list not found response has a 3xx status code
func (o *AvatarCandidateListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this avatar candidate list not found response has a 4xx status code
func (o *AvatarCandidateListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this avatar candidate list not found response has a 5xx status code
func (o *AvatarCandidateListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this avatar candidate list not found response a status code equal to that given
func (o *AvatarCandidateListNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *AvatarCandidateListNotFound) Error() string {
	return fmt.Sprintf("[GET /v0.1/apps/{app-slug}/avatar-candidates][%d] avatarCandidateListNotFound  %+v", 404, o.Payload)
}

func (o *AvatarCandidateListNotFound) String() string {
	return fmt.Sprintf("[GET /v0.1/apps/{app-slug}/avatar-candidates][%d] avatarCandidateListNotFound  %+v", 404, o.Payload)
}

func (o *AvatarCandidateListNotFound) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AvatarCandidateListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAvatarCandidateListInternalServerError creates a AvatarCandidateListInternalServerError with default headers values
func NewAvatarCandidateListInternalServerError() *AvatarCandidateListInternalServerError {
	return &AvatarCandidateListInternalServerError{}
}

/*
AvatarCandidateListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type AvatarCandidateListInternalServerError struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this avatar candidate list internal server error response has a 2xx status code
func (o *AvatarCandidateListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this avatar candidate list internal server error response has a 3xx status code
func (o *AvatarCandidateListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this avatar candidate list internal server error response has a 4xx status code
func (o *AvatarCandidateListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this avatar candidate list internal server error response has a 5xx status code
func (o *AvatarCandidateListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this avatar candidate list internal server error response a status code equal to that given
func (o *AvatarCandidateListInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *AvatarCandidateListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v0.1/apps/{app-slug}/avatar-candidates][%d] avatarCandidateListInternalServerError  %+v", 500, o.Payload)
}

func (o *AvatarCandidateListInternalServerError) String() string {
	return fmt.Sprintf("[GET /v0.1/apps/{app-slug}/avatar-candidates][%d] avatarCandidateListInternalServerError  %+v", 500, o.Payload)
}

func (o *AvatarCandidateListInternalServerError) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *AvatarCandidateListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
