// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Staffbase/bitrise-api/go/models"
)

// BuildRequestListReader is a Reader for the BuildRequestList structure.
type BuildRequestListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BuildRequestListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBuildRequestListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewBuildRequestListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewBuildRequestListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewBuildRequestListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewBuildRequestListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewBuildRequestListOK creates a BuildRequestListOK with default headers values
func NewBuildRequestListOK() *BuildRequestListOK {
	return &BuildRequestListOK{}
}

/*
BuildRequestListOK describes a response with status code 200, with default header values.

OK
*/
type BuildRequestListOK struct {
	Payload *models.V0BuildRequestListResponseModel
}

// IsSuccess returns true when this build request list o k response has a 2xx status code
func (o *BuildRequestListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this build request list o k response has a 3xx status code
func (o *BuildRequestListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this build request list o k response has a 4xx status code
func (o *BuildRequestListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this build request list o k response has a 5xx status code
func (o *BuildRequestListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this build request list o k response a status code equal to that given
func (o *BuildRequestListOK) IsCode(code int) bool {
	return code == 200
}

func (o *BuildRequestListOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/build-requests][%d] buildRequestListOK  %+v", 200, o.Payload)
}

func (o *BuildRequestListOK) String() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/build-requests][%d] buildRequestListOK  %+v", 200, o.Payload)
}

func (o *BuildRequestListOK) GetPayload() *models.V0BuildRequestListResponseModel {
	return o.Payload
}

func (o *BuildRequestListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V0BuildRequestListResponseModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBuildRequestListBadRequest creates a BuildRequestListBadRequest with default headers values
func NewBuildRequestListBadRequest() *BuildRequestListBadRequest {
	return &BuildRequestListBadRequest{}
}

/*
BuildRequestListBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type BuildRequestListBadRequest struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this build request list bad request response has a 2xx status code
func (o *BuildRequestListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this build request list bad request response has a 3xx status code
func (o *BuildRequestListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this build request list bad request response has a 4xx status code
func (o *BuildRequestListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this build request list bad request response has a 5xx status code
func (o *BuildRequestListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this build request list bad request response a status code equal to that given
func (o *BuildRequestListBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *BuildRequestListBadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/build-requests][%d] buildRequestListBadRequest  %+v", 400, o.Payload)
}

func (o *BuildRequestListBadRequest) String() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/build-requests][%d] buildRequestListBadRequest  %+v", 400, o.Payload)
}

func (o *BuildRequestListBadRequest) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *BuildRequestListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBuildRequestListUnauthorized creates a BuildRequestListUnauthorized with default headers values
func NewBuildRequestListUnauthorized() *BuildRequestListUnauthorized {
	return &BuildRequestListUnauthorized{}
}

/*
BuildRequestListUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type BuildRequestListUnauthorized struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this build request list unauthorized response has a 2xx status code
func (o *BuildRequestListUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this build request list unauthorized response has a 3xx status code
func (o *BuildRequestListUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this build request list unauthorized response has a 4xx status code
func (o *BuildRequestListUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this build request list unauthorized response has a 5xx status code
func (o *BuildRequestListUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this build request list unauthorized response a status code equal to that given
func (o *BuildRequestListUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *BuildRequestListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/build-requests][%d] buildRequestListUnauthorized  %+v", 401, o.Payload)
}

func (o *BuildRequestListUnauthorized) String() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/build-requests][%d] buildRequestListUnauthorized  %+v", 401, o.Payload)
}

func (o *BuildRequestListUnauthorized) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *BuildRequestListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBuildRequestListNotFound creates a BuildRequestListNotFound with default headers values
func NewBuildRequestListNotFound() *BuildRequestListNotFound {
	return &BuildRequestListNotFound{}
}

/*
BuildRequestListNotFound describes a response with status code 404, with default header values.

Not Found
*/
type BuildRequestListNotFound struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this build request list not found response has a 2xx status code
func (o *BuildRequestListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this build request list not found response has a 3xx status code
func (o *BuildRequestListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this build request list not found response has a 4xx status code
func (o *BuildRequestListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this build request list not found response has a 5xx status code
func (o *BuildRequestListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this build request list not found response a status code equal to that given
func (o *BuildRequestListNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *BuildRequestListNotFound) Error() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/build-requests][%d] buildRequestListNotFound  %+v", 404, o.Payload)
}

func (o *BuildRequestListNotFound) String() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/build-requests][%d] buildRequestListNotFound  %+v", 404, o.Payload)
}

func (o *BuildRequestListNotFound) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *BuildRequestListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBuildRequestListInternalServerError creates a BuildRequestListInternalServerError with default headers values
func NewBuildRequestListInternalServerError() *BuildRequestListInternalServerError {
	return &BuildRequestListInternalServerError{}
}

/*
BuildRequestListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type BuildRequestListInternalServerError struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this build request list internal server error response has a 2xx status code
func (o *BuildRequestListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this build request list internal server error response has a 3xx status code
func (o *BuildRequestListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this build request list internal server error response has a 4xx status code
func (o *BuildRequestListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this build request list internal server error response has a 5xx status code
func (o *BuildRequestListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this build request list internal server error response a status code equal to that given
func (o *BuildRequestListInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *BuildRequestListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/build-requests][%d] buildRequestListInternalServerError  %+v", 500, o.Payload)
}

func (o *BuildRequestListInternalServerError) String() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/build-requests][%d] buildRequestListInternalServerError  %+v", 500, o.Payload)
}

func (o *BuildRequestListInternalServerError) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *BuildRequestListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
