// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLocalBuildListParams creates a new LocalBuildListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLocalBuildListParams() *LocalBuildListParams {
	return &LocalBuildListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLocalBuildListParamsWithTimeout creates a new LocalBuildListParams object
// with the ability to set a timeout on a request.
func NewLocalBuildListParamsWithTimeout(timeout time.Duration) *LocalBuildListParams {
	return &LocalBuildListParams{
		timeout: timeout,
	}
}

// NewLocalBuildListParamsWithContext creates a new LocalBuildListParams object
// with the ability to set a context for a request.
func NewLocalBuildListParamsWithContext(ctx context.Context) *LocalBuildListParams {
	return &LocalBuildListParams{
		Context: ctx,
	}
}

// NewLocalBuildListParamsWithHTTPClient creates a new LocalBuildListParams object
// with the ability to set a custom HTTPClient for a request.
func NewLocalBuildListParamsWithHTTPClient(client *http.Client) *LocalBuildListParams {
	return &LocalBuildListParams{
		HTTPClient: client,
	}
}

/*
LocalBuildListParams contains all the parameters to send to the API endpoint

	for the local build list operation.

	Typically these are written to a http.Request.
*/
type LocalBuildListParams struct {

	/* After.

	   List local builds run after a given date (RFC3339 time format)
	*/
	After *string

	/* AppSlug.

	   App slug
	*/
	AppSlug string

	/* Before.

	   List local builds run before a given date (RFC3339 time format) - was called 'next' earlier
	*/
	Before *string

	/* Limit.

	   Max number of elements per page (default: 10)
	*/
	Limit *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the local build list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LocalBuildListParams) WithDefaults() *LocalBuildListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the local build list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LocalBuildListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the local build list params
func (o *LocalBuildListParams) WithTimeout(timeout time.Duration) *LocalBuildListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the local build list params
func (o *LocalBuildListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the local build list params
func (o *LocalBuildListParams) WithContext(ctx context.Context) *LocalBuildListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the local build list params
func (o *LocalBuildListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the local build list params
func (o *LocalBuildListParams) WithHTTPClient(client *http.Client) *LocalBuildListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the local build list params
func (o *LocalBuildListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAfter adds the after to the local build list params
func (o *LocalBuildListParams) WithAfter(after *string) *LocalBuildListParams {
	o.SetAfter(after)
	return o
}

// SetAfter adds the after to the local build list params
func (o *LocalBuildListParams) SetAfter(after *string) {
	o.After = after
}

// WithAppSlug adds the appSlug to the local build list params
func (o *LocalBuildListParams) WithAppSlug(appSlug string) *LocalBuildListParams {
	o.SetAppSlug(appSlug)
	return o
}

// SetAppSlug adds the appSlug to the local build list params
func (o *LocalBuildListParams) SetAppSlug(appSlug string) {
	o.AppSlug = appSlug
}

// WithBefore adds the before to the local build list params
func (o *LocalBuildListParams) WithBefore(before *string) *LocalBuildListParams {
	o.SetBefore(before)
	return o
}

// SetBefore adds the before to the local build list params
func (o *LocalBuildListParams) SetBefore(before *string) {
	o.Before = before
}

// WithLimit adds the limit to the local build list params
func (o *LocalBuildListParams) WithLimit(limit *int64) *LocalBuildListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the local build list params
func (o *LocalBuildListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WriteToRequest writes these params to a swagger request
func (o *LocalBuildListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.After != nil {

		// query param after
		var qrAfter string

		if o.After != nil {
			qrAfter = *o.After
		}
		qAfter := qrAfter
		if qAfter != "" {

			if err := r.SetQueryParam("after", qAfter); err != nil {
				return err
			}
		}
	}

	// path param app-slug
	if err := r.SetPathParam("app-slug", o.AppSlug); err != nil {
		return err
	}

	if o.Before != nil {

		// query param before
		var qrBefore string

		if o.Before != nil {
			qrBefore = *o.Before
		}
		qBefore := qrBefore
		if qBefore != "" {

			if err := r.SetQueryParam("before", qBefore); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
