// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/Staffbase/bitrise-api/go/models"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// OrganizationGroupAddReader is a Reader for the OrganizationGroupAdd structure.
type OrganizationGroupAddReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationGroupAddReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewOrganizationGroupAddCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewOrganizationGroupAddUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewOrganizationGroupAddForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewOrganizationGroupAddNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /organizations/{org-slug}/groups] organization-group-add", response, response.Code())
	}
}

// NewOrganizationGroupAddCreated creates a OrganizationGroupAddCreated with default headers values
func NewOrganizationGroupAddCreated() *OrganizationGroupAddCreated {
	return &OrganizationGroupAddCreated{}
}

// OrganizationGroupAddCreated describes a response with status code 201, with default header values.
//
// Created
type OrganizationGroupAddCreated struct {
	Payload *models.ServiceDtoGroup
}

// IsSuccess returns true when this organization group add created response has a 2xx status code
func (o *OrganizationGroupAddCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organization group add created response has a 3xx status code
func (o *OrganizationGroupAddCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization group add created response has a 4xx status code
func (o *OrganizationGroupAddCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this organization group add created response has a 5xx status code
func (o *OrganizationGroupAddCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this organization group add created response a status code equal to that given
func (o *OrganizationGroupAddCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the organization group add created response
func (o *OrganizationGroupAddCreated) Code() int {
	return 201
}

func (o *OrganizationGroupAddCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{org-slug}/groups][%d] organizationGroupAddCreated %s", 201, payload)
}

func (o *OrganizationGroupAddCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{org-slug}/groups][%d] organizationGroupAddCreated %s", 201, payload)
}

func (o *OrganizationGroupAddCreated) GetPayload() *models.ServiceDtoGroup {
	return o.Payload
}

func (o *OrganizationGroupAddCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceDtoGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewOrganizationGroupAddUnauthorized creates a OrganizationGroupAddUnauthorized with default headers values
func NewOrganizationGroupAddUnauthorized() *OrganizationGroupAddUnauthorized {
	return &OrganizationGroupAddUnauthorized{}
}

// OrganizationGroupAddUnauthorized describes a response with status code 401, with default header values.
//
// Unauthorized
type OrganizationGroupAddUnauthorized struct {
	Payload *models.ServiceProxyErrorRespModel
}

// IsSuccess returns true when this organization group add unauthorized response has a 2xx status code
func (o *OrganizationGroupAddUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this organization group add unauthorized response has a 3xx status code
func (o *OrganizationGroupAddUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization group add unauthorized response has a 4xx status code
func (o *OrganizationGroupAddUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this organization group add unauthorized response has a 5xx status code
func (o *OrganizationGroupAddUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this organization group add unauthorized response a status code equal to that given
func (o *OrganizationGroupAddUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the organization group add unauthorized response
func (o *OrganizationGroupAddUnauthorized) Code() int {
	return 401
}

func (o *OrganizationGroupAddUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{org-slug}/groups][%d] organizationGroupAddUnauthorized %s", 401, payload)
}

func (o *OrganizationGroupAddUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{org-slug}/groups][%d] organizationGroupAddUnauthorized %s", 401, payload)
}

func (o *OrganizationGroupAddUnauthorized) GetPayload() *models.ServiceProxyErrorRespModel {
	return o.Payload
}

func (o *OrganizationGroupAddUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceProxyErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewOrganizationGroupAddForbidden creates a OrganizationGroupAddForbidden with default headers values
func NewOrganizationGroupAddForbidden() *OrganizationGroupAddForbidden {
	return &OrganizationGroupAddForbidden{}
}

// OrganizationGroupAddForbidden describes a response with status code 403, with default header values.
//
// Forbidden
type OrganizationGroupAddForbidden struct {
	Payload *models.ServiceProxyErrorRespModel
}

// IsSuccess returns true when this organization group add forbidden response has a 2xx status code
func (o *OrganizationGroupAddForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this organization group add forbidden response has a 3xx status code
func (o *OrganizationGroupAddForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization group add forbidden response has a 4xx status code
func (o *OrganizationGroupAddForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this organization group add forbidden response has a 5xx status code
func (o *OrganizationGroupAddForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this organization group add forbidden response a status code equal to that given
func (o *OrganizationGroupAddForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the organization group add forbidden response
func (o *OrganizationGroupAddForbidden) Code() int {
	return 403
}

func (o *OrganizationGroupAddForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{org-slug}/groups][%d] organizationGroupAddForbidden %s", 403, payload)
}

func (o *OrganizationGroupAddForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{org-slug}/groups][%d] organizationGroupAddForbidden %s", 403, payload)
}

func (o *OrganizationGroupAddForbidden) GetPayload() *models.ServiceProxyErrorRespModel {
	return o.Payload
}

func (o *OrganizationGroupAddForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceProxyErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewOrganizationGroupAddNotFound creates a OrganizationGroupAddNotFound with default headers values
func NewOrganizationGroupAddNotFound() *OrganizationGroupAddNotFound {
	return &OrganizationGroupAddNotFound{}
}

// OrganizationGroupAddNotFound describes a response with status code 404, with default header values.
//
// Not found
type OrganizationGroupAddNotFound struct {
	Payload *models.ServiceProxyErrorRespModel
}

// IsSuccess returns true when this organization group add not found response has a 2xx status code
func (o *OrganizationGroupAddNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this organization group add not found response has a 3xx status code
func (o *OrganizationGroupAddNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization group add not found response has a 4xx status code
func (o *OrganizationGroupAddNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this organization group add not found response has a 5xx status code
func (o *OrganizationGroupAddNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this organization group add not found response a status code equal to that given
func (o *OrganizationGroupAddNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the organization group add not found response
func (o *OrganizationGroupAddNotFound) Code() int {
	return 404
}

func (o *OrganizationGroupAddNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{org-slug}/groups][%d] organizationGroupAddNotFound %s", 404, payload)
}

func (o *OrganizationGroupAddNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{org-slug}/groups][%d] organizationGroupAddNotFound %s", 404, payload)
}

func (o *OrganizationGroupAddNotFound) GetPayload() *models.ServiceProxyErrorRespModel {
	return o.Payload
}

func (o *OrganizationGroupAddNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceProxyErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// OrganizationGroupAddBody organization group add body
//
// swagger:model OrganizationGroupAddBody
type OrganizationGroupAddBody struct {

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this organization group add body
func (o *OrganizationGroupAddBody) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this organization group add body based on context it is used
func (o *OrganizationGroupAddBody) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *OrganizationGroupAddBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *OrganizationGroupAddBody) UnmarshalBinary(b []byte) error {
	var res OrganizationGroupAddBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
