// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"
	"strconv"

	"github.com/Staffbase/bitrise-api/go/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// OrganizationSecretsListReader is a Reader for the OrganizationSecretsList structure.
type OrganizationSecretsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationSecretsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationSecretsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewOrganizationSecretsListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewOrganizationSecretsListForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewOrganizationSecretsListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /organizations/{org-slug}/secrets] organization-secrets-list", response, response.Code())
	}
}

// NewOrganizationSecretsListOK creates a OrganizationSecretsListOK with default headers values
func NewOrganizationSecretsListOK() *OrganizationSecretsListOK {
	return &OrganizationSecretsListOK{}
}

// OrganizationSecretsListOK describes a response with status code 200, with default header values.
//
// Ok
type OrganizationSecretsListOK struct {
	Payload *OrganizationSecretsListOKBody
}

// IsSuccess returns true when this organization secrets list o k response has a 2xx status code
func (o *OrganizationSecretsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organization secrets list o k response has a 3xx status code
func (o *OrganizationSecretsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization secrets list o k response has a 4xx status code
func (o *OrganizationSecretsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this organization secrets list o k response has a 5xx status code
func (o *OrganizationSecretsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this organization secrets list o k response a status code equal to that given
func (o *OrganizationSecretsListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the organization secrets list o k response
func (o *OrganizationSecretsListOK) Code() int {
	return 200
}

func (o *OrganizationSecretsListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{org-slug}/secrets][%d] organizationSecretsListOK %s", 200, payload)
}

func (o *OrganizationSecretsListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{org-slug}/secrets][%d] organizationSecretsListOK %s", 200, payload)
}

func (o *OrganizationSecretsListOK) GetPayload() *OrganizationSecretsListOKBody {
	return o.Payload
}

func (o *OrganizationSecretsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(OrganizationSecretsListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewOrganizationSecretsListUnauthorized creates a OrganizationSecretsListUnauthorized with default headers values
func NewOrganizationSecretsListUnauthorized() *OrganizationSecretsListUnauthorized {
	return &OrganizationSecretsListUnauthorized{}
}

// OrganizationSecretsListUnauthorized describes a response with status code 401, with default header values.
//
// Unauthorized
type OrganizationSecretsListUnauthorized struct {
	Payload *models.ServiceProxyErrorRespModel
}

// IsSuccess returns true when this organization secrets list unauthorized response has a 2xx status code
func (o *OrganizationSecretsListUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this organization secrets list unauthorized response has a 3xx status code
func (o *OrganizationSecretsListUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization secrets list unauthorized response has a 4xx status code
func (o *OrganizationSecretsListUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this organization secrets list unauthorized response has a 5xx status code
func (o *OrganizationSecretsListUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this organization secrets list unauthorized response a status code equal to that given
func (o *OrganizationSecretsListUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the organization secrets list unauthorized response
func (o *OrganizationSecretsListUnauthorized) Code() int {
	return 401
}

func (o *OrganizationSecretsListUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{org-slug}/secrets][%d] organizationSecretsListUnauthorized %s", 401, payload)
}

func (o *OrganizationSecretsListUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{org-slug}/secrets][%d] organizationSecretsListUnauthorized %s", 401, payload)
}

func (o *OrganizationSecretsListUnauthorized) GetPayload() *models.ServiceProxyErrorRespModel {
	return o.Payload
}

func (o *OrganizationSecretsListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceProxyErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewOrganizationSecretsListForbidden creates a OrganizationSecretsListForbidden with default headers values
func NewOrganizationSecretsListForbidden() *OrganizationSecretsListForbidden {
	return &OrganizationSecretsListForbidden{}
}

// OrganizationSecretsListForbidden describes a response with status code 403, with default header values.
//
// Forbidden
type OrganizationSecretsListForbidden struct {
	Payload *models.ServiceProxyErrorRespModel
}

// IsSuccess returns true when this organization secrets list forbidden response has a 2xx status code
func (o *OrganizationSecretsListForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this organization secrets list forbidden response has a 3xx status code
func (o *OrganizationSecretsListForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization secrets list forbidden response has a 4xx status code
func (o *OrganizationSecretsListForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this organization secrets list forbidden response has a 5xx status code
func (o *OrganizationSecretsListForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this organization secrets list forbidden response a status code equal to that given
func (o *OrganizationSecretsListForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the organization secrets list forbidden response
func (o *OrganizationSecretsListForbidden) Code() int {
	return 403
}

func (o *OrganizationSecretsListForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{org-slug}/secrets][%d] organizationSecretsListForbidden %s", 403, payload)
}

func (o *OrganizationSecretsListForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{org-slug}/secrets][%d] organizationSecretsListForbidden %s", 403, payload)
}

func (o *OrganizationSecretsListForbidden) GetPayload() *models.ServiceProxyErrorRespModel {
	return o.Payload
}

func (o *OrganizationSecretsListForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceProxyErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewOrganizationSecretsListNotFound creates a OrganizationSecretsListNotFound with default headers values
func NewOrganizationSecretsListNotFound() *OrganizationSecretsListNotFound {
	return &OrganizationSecretsListNotFound{}
}

// OrganizationSecretsListNotFound describes a response with status code 404, with default header values.
//
// Not found
type OrganizationSecretsListNotFound struct {
	Payload *models.ServiceProxyErrorRespModel
}

// IsSuccess returns true when this organization secrets list not found response has a 2xx status code
func (o *OrganizationSecretsListNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this organization secrets list not found response has a 3xx status code
func (o *OrganizationSecretsListNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization secrets list not found response has a 4xx status code
func (o *OrganizationSecretsListNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this organization secrets list not found response has a 5xx status code
func (o *OrganizationSecretsListNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this organization secrets list not found response a status code equal to that given
func (o *OrganizationSecretsListNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the organization secrets list not found response
func (o *OrganizationSecretsListNotFound) Code() int {
	return 404
}

func (o *OrganizationSecretsListNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{org-slug}/secrets][%d] organizationSecretsListNotFound %s", 404, payload)
}

func (o *OrganizationSecretsListNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{org-slug}/secrets][%d] organizationSecretsListNotFound %s", 404, payload)
}

func (o *OrganizationSecretsListNotFound) GetPayload() *models.ServiceProxyErrorRespModel {
	return o.Payload
}

func (o *OrganizationSecretsListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceProxyErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// OrganizationSecretsListOKBody organization secrets list o k body
//
// swagger:model OrganizationSecretsListOKBody
type OrganizationSecretsListOKBody struct {

	// secrets
	Secrets []*models.ServiceDtoCreatedSecretNoValue `json:"secrets"`
}

// Validate validates this organization secrets list o k body
func (o *OrganizationSecretsListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSecrets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *OrganizationSecretsListOKBody) validateSecrets(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Secrets) { // not required
		return nil
	}

	for i := 0; i < len(o.Secrets); i++ {
		if typeutils.IsZero(o.Secrets[i]) { // not required
			continue
		}

		if o.Secrets[i] != nil {
			if err := o.Secrets[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("organizationSecretsListOK" + "." + "secrets" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("organizationSecretsListOK" + "." + "secrets" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this organization secrets list o k body based on the context it is used
func (o *OrganizationSecretsListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateSecrets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *OrganizationSecretsListOKBody) contextValidateSecrets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Secrets); i++ {

		if o.Secrets[i] != nil {

			if typeutils.IsZero(o.Secrets[i]) { // not required
				return nil
			}

			if err := o.Secrets[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("organizationSecretsListOK" + "." + "secrets" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("organizationSecretsListOK" + "." + "secrets" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *OrganizationSecretsListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *OrganizationSecretsListOKBody) UnmarshalBinary(b []byte) error {
	var res OrganizationSecretsListOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
