// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Staffbase/bitrise-api/go/models"
)

// OutgoingWebhookUpdateReader is a Reader for the OutgoingWebhookUpdate structure.
type OutgoingWebhookUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OutgoingWebhookUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOutgoingWebhookUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewOutgoingWebhookUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewOutgoingWebhookUpdateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewOutgoingWebhookUpdateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewOutgoingWebhookUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOutgoingWebhookUpdateOK creates a OutgoingWebhookUpdateOK with default headers values
func NewOutgoingWebhookUpdateOK() *OutgoingWebhookUpdateOK {
	return &OutgoingWebhookUpdateOK{}
}

/*
OutgoingWebhookUpdateOK describes a response with status code 200, with default header values.

OK
*/
type OutgoingWebhookUpdateOK struct {
	Payload *models.V0AppWebhookResponseModel
}

// IsSuccess returns true when this outgoing webhook update o k response has a 2xx status code
func (o *OutgoingWebhookUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this outgoing webhook update o k response has a 3xx status code
func (o *OutgoingWebhookUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this outgoing webhook update o k response has a 4xx status code
func (o *OutgoingWebhookUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this outgoing webhook update o k response has a 5xx status code
func (o *OutgoingWebhookUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this outgoing webhook update o k response a status code equal to that given
func (o *OutgoingWebhookUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *OutgoingWebhookUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookUpdateOK  %+v", 200, o.Payload)
}

func (o *OutgoingWebhookUpdateOK) String() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookUpdateOK  %+v", 200, o.Payload)
}

func (o *OutgoingWebhookUpdateOK) GetPayload() *models.V0AppWebhookResponseModel {
	return o.Payload
}

func (o *OutgoingWebhookUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V0AppWebhookResponseModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOutgoingWebhookUpdateBadRequest creates a OutgoingWebhookUpdateBadRequest with default headers values
func NewOutgoingWebhookUpdateBadRequest() *OutgoingWebhookUpdateBadRequest {
	return &OutgoingWebhookUpdateBadRequest{}
}

/*
OutgoingWebhookUpdateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type OutgoingWebhookUpdateBadRequest struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this outgoing webhook update bad request response has a 2xx status code
func (o *OutgoingWebhookUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this outgoing webhook update bad request response has a 3xx status code
func (o *OutgoingWebhookUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this outgoing webhook update bad request response has a 4xx status code
func (o *OutgoingWebhookUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this outgoing webhook update bad request response has a 5xx status code
func (o *OutgoingWebhookUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this outgoing webhook update bad request response a status code equal to that given
func (o *OutgoingWebhookUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *OutgoingWebhookUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *OutgoingWebhookUpdateBadRequest) String() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *OutgoingWebhookUpdateBadRequest) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *OutgoingWebhookUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOutgoingWebhookUpdateUnauthorized creates a OutgoingWebhookUpdateUnauthorized with default headers values
func NewOutgoingWebhookUpdateUnauthorized() *OutgoingWebhookUpdateUnauthorized {
	return &OutgoingWebhookUpdateUnauthorized{}
}

/*
OutgoingWebhookUpdateUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type OutgoingWebhookUpdateUnauthorized struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this outgoing webhook update unauthorized response has a 2xx status code
func (o *OutgoingWebhookUpdateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this outgoing webhook update unauthorized response has a 3xx status code
func (o *OutgoingWebhookUpdateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this outgoing webhook update unauthorized response has a 4xx status code
func (o *OutgoingWebhookUpdateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this outgoing webhook update unauthorized response has a 5xx status code
func (o *OutgoingWebhookUpdateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this outgoing webhook update unauthorized response a status code equal to that given
func (o *OutgoingWebhookUpdateUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *OutgoingWebhookUpdateUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookUpdateUnauthorized  %+v", 401, o.Payload)
}

func (o *OutgoingWebhookUpdateUnauthorized) String() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookUpdateUnauthorized  %+v", 401, o.Payload)
}

func (o *OutgoingWebhookUpdateUnauthorized) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *OutgoingWebhookUpdateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOutgoingWebhookUpdateNotFound creates a OutgoingWebhookUpdateNotFound with default headers values
func NewOutgoingWebhookUpdateNotFound() *OutgoingWebhookUpdateNotFound {
	return &OutgoingWebhookUpdateNotFound{}
}

/*
OutgoingWebhookUpdateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type OutgoingWebhookUpdateNotFound struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this outgoing webhook update not found response has a 2xx status code
func (o *OutgoingWebhookUpdateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this outgoing webhook update not found response has a 3xx status code
func (o *OutgoingWebhookUpdateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this outgoing webhook update not found response has a 4xx status code
func (o *OutgoingWebhookUpdateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this outgoing webhook update not found response has a 5xx status code
func (o *OutgoingWebhookUpdateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this outgoing webhook update not found response a status code equal to that given
func (o *OutgoingWebhookUpdateNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *OutgoingWebhookUpdateNotFound) Error() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookUpdateNotFound  %+v", 404, o.Payload)
}

func (o *OutgoingWebhookUpdateNotFound) String() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookUpdateNotFound  %+v", 404, o.Payload)
}

func (o *OutgoingWebhookUpdateNotFound) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *OutgoingWebhookUpdateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOutgoingWebhookUpdateInternalServerError creates a OutgoingWebhookUpdateInternalServerError with default headers values
func NewOutgoingWebhookUpdateInternalServerError() *OutgoingWebhookUpdateInternalServerError {
	return &OutgoingWebhookUpdateInternalServerError{}
}

/*
OutgoingWebhookUpdateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type OutgoingWebhookUpdateInternalServerError struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this outgoing webhook update internal server error response has a 2xx status code
func (o *OutgoingWebhookUpdateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this outgoing webhook update internal server error response has a 3xx status code
func (o *OutgoingWebhookUpdateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this outgoing webhook update internal server error response has a 4xx status code
func (o *OutgoingWebhookUpdateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this outgoing webhook update internal server error response has a 5xx status code
func (o *OutgoingWebhookUpdateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this outgoing webhook update internal server error response a status code equal to that given
func (o *OutgoingWebhookUpdateInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *OutgoingWebhookUpdateInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookUpdateInternalServerError  %+v", 500, o.Payload)
}

func (o *OutgoingWebhookUpdateInternalServerError) String() string {
	return fmt.Sprintf("[PUT /apps/{app-slug}/outgoing-webhooks/{app-webhook-slug}][%d] outgoingWebhookUpdateInternalServerError  %+v", 500, o.Payload)
}

func (o *OutgoingWebhookUpdateInternalServerError) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *OutgoingWebhookUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
