// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Staffbase/bitrise-api/go/models"
)

// ProvisioningProfileShowReader is a Reader for the ProvisioningProfileShow structure.
type ProvisioningProfileShowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProvisioningProfileShowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProvisioningProfileShowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewProvisioningProfileShowBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewProvisioningProfileShowUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewProvisioningProfileShowNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewProvisioningProfileShowInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}] provisioning-profile-show", response, response.Code())
	}
}

// NewProvisioningProfileShowOK creates a ProvisioningProfileShowOK with default headers values
func NewProvisioningProfileShowOK() *ProvisioningProfileShowOK {
	return &ProvisioningProfileShowOK{}
}

/*
ProvisioningProfileShowOK describes a response with status code 200, with default header values.

OK
*/
type ProvisioningProfileShowOK struct {
	Payload *models.V0ProvisionProfileResponseModel
}

// IsSuccess returns true when this provisioning profile show o k response has a 2xx status code
func (o *ProvisioningProfileShowOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this provisioning profile show o k response has a 3xx status code
func (o *ProvisioningProfileShowOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this provisioning profile show o k response has a 4xx status code
func (o *ProvisioningProfileShowOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this provisioning profile show o k response has a 5xx status code
func (o *ProvisioningProfileShowOK) IsServerError() bool {
	return false
}

// IsCode returns true when this provisioning profile show o k response a status code equal to that given
func (o *ProvisioningProfileShowOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the provisioning profile show o k response
func (o *ProvisioningProfileShowOK) Code() int {
	return 200
}

func (o *ProvisioningProfileShowOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}][%d] provisioningProfileShowOK  %+v", 200, o.Payload)
}

func (o *ProvisioningProfileShowOK) String() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}][%d] provisioningProfileShowOK  %+v", 200, o.Payload)
}

func (o *ProvisioningProfileShowOK) GetPayload() *models.V0ProvisionProfileResponseModel {
	return o.Payload
}

func (o *ProvisioningProfileShowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V0ProvisionProfileResponseModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProvisioningProfileShowBadRequest creates a ProvisioningProfileShowBadRequest with default headers values
func NewProvisioningProfileShowBadRequest() *ProvisioningProfileShowBadRequest {
	return &ProvisioningProfileShowBadRequest{}
}

/*
ProvisioningProfileShowBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ProvisioningProfileShowBadRequest struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this provisioning profile show bad request response has a 2xx status code
func (o *ProvisioningProfileShowBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this provisioning profile show bad request response has a 3xx status code
func (o *ProvisioningProfileShowBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this provisioning profile show bad request response has a 4xx status code
func (o *ProvisioningProfileShowBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this provisioning profile show bad request response has a 5xx status code
func (o *ProvisioningProfileShowBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this provisioning profile show bad request response a status code equal to that given
func (o *ProvisioningProfileShowBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the provisioning profile show bad request response
func (o *ProvisioningProfileShowBadRequest) Code() int {
	return 400
}

func (o *ProvisioningProfileShowBadRequest) Error() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}][%d] provisioningProfileShowBadRequest  %+v", 400, o.Payload)
}

func (o *ProvisioningProfileShowBadRequest) String() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}][%d] provisioningProfileShowBadRequest  %+v", 400, o.Payload)
}

func (o *ProvisioningProfileShowBadRequest) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *ProvisioningProfileShowBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProvisioningProfileShowUnauthorized creates a ProvisioningProfileShowUnauthorized with default headers values
func NewProvisioningProfileShowUnauthorized() *ProvisioningProfileShowUnauthorized {
	return &ProvisioningProfileShowUnauthorized{}
}

/*
ProvisioningProfileShowUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ProvisioningProfileShowUnauthorized struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this provisioning profile show unauthorized response has a 2xx status code
func (o *ProvisioningProfileShowUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this provisioning profile show unauthorized response has a 3xx status code
func (o *ProvisioningProfileShowUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this provisioning profile show unauthorized response has a 4xx status code
func (o *ProvisioningProfileShowUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this provisioning profile show unauthorized response has a 5xx status code
func (o *ProvisioningProfileShowUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this provisioning profile show unauthorized response a status code equal to that given
func (o *ProvisioningProfileShowUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the provisioning profile show unauthorized response
func (o *ProvisioningProfileShowUnauthorized) Code() int {
	return 401
}

func (o *ProvisioningProfileShowUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}][%d] provisioningProfileShowUnauthorized  %+v", 401, o.Payload)
}

func (o *ProvisioningProfileShowUnauthorized) String() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}][%d] provisioningProfileShowUnauthorized  %+v", 401, o.Payload)
}

func (o *ProvisioningProfileShowUnauthorized) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *ProvisioningProfileShowUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProvisioningProfileShowNotFound creates a ProvisioningProfileShowNotFound with default headers values
func NewProvisioningProfileShowNotFound() *ProvisioningProfileShowNotFound {
	return &ProvisioningProfileShowNotFound{}
}

/*
ProvisioningProfileShowNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ProvisioningProfileShowNotFound struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this provisioning profile show not found response has a 2xx status code
func (o *ProvisioningProfileShowNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this provisioning profile show not found response has a 3xx status code
func (o *ProvisioningProfileShowNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this provisioning profile show not found response has a 4xx status code
func (o *ProvisioningProfileShowNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this provisioning profile show not found response has a 5xx status code
func (o *ProvisioningProfileShowNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this provisioning profile show not found response a status code equal to that given
func (o *ProvisioningProfileShowNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the provisioning profile show not found response
func (o *ProvisioningProfileShowNotFound) Code() int {
	return 404
}

func (o *ProvisioningProfileShowNotFound) Error() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}][%d] provisioningProfileShowNotFound  %+v", 404, o.Payload)
}

func (o *ProvisioningProfileShowNotFound) String() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}][%d] provisioningProfileShowNotFound  %+v", 404, o.Payload)
}

func (o *ProvisioningProfileShowNotFound) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *ProvisioningProfileShowNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProvisioningProfileShowInternalServerError creates a ProvisioningProfileShowInternalServerError with default headers values
func NewProvisioningProfileShowInternalServerError() *ProvisioningProfileShowInternalServerError {
	return &ProvisioningProfileShowInternalServerError{}
}

/*
ProvisioningProfileShowInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ProvisioningProfileShowInternalServerError struct {
	Payload *models.ServiceStandardErrorRespModel
}

// IsSuccess returns true when this provisioning profile show internal server error response has a 2xx status code
func (o *ProvisioningProfileShowInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this provisioning profile show internal server error response has a 3xx status code
func (o *ProvisioningProfileShowInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this provisioning profile show internal server error response has a 4xx status code
func (o *ProvisioningProfileShowInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this provisioning profile show internal server error response has a 5xx status code
func (o *ProvisioningProfileShowInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this provisioning profile show internal server error response a status code equal to that given
func (o *ProvisioningProfileShowInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the provisioning profile show internal server error response
func (o *ProvisioningProfileShowInternalServerError) Code() int {
	return 500
}

func (o *ProvisioningProfileShowInternalServerError) Error() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}][%d] provisioningProfileShowInternalServerError  %+v", 500, o.Payload)
}

func (o *ProvisioningProfileShowInternalServerError) String() string {
	return fmt.Sprintf("[GET /apps/{app-slug}/provisioning-profiles/{provisioning-profile-slug}][%d] provisioningProfileShowInternalServerError  %+v", 500, o.Payload)
}

func (o *ProvisioningProfileShowInternalServerError) GetPayload() *models.ServiceStandardErrorRespModel {
	return o.Payload
}

func (o *ProvisioningProfileShowInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceStandardErrorRespModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
