/*
Bitrise API

Official REST API for Bitrise.io

API version: 0.1
Contact: letsconnect@bitrise.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V0UserPlanRespModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0UserPlanRespModel{}

// V0UserPlanRespModel struct for V0UserPlanRespModel
type V0UserPlanRespModel struct {
	Data *V0UserPlanDataModel `json:"data,omitempty"`
}

// NewV0UserPlanRespModel instantiates a new V0UserPlanRespModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0UserPlanRespModel() *V0UserPlanRespModel {
	this := V0UserPlanRespModel{}
	return &this
}

// NewV0UserPlanRespModelWithDefaults instantiates a new V0UserPlanRespModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0UserPlanRespModelWithDefaults() *V0UserPlanRespModel {
	this := V0UserPlanRespModel{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *V0UserPlanRespModel) GetData() V0UserPlanDataModel {
	if o == nil || IsNil(o.Data) {
		var ret V0UserPlanDataModel
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0UserPlanRespModel) GetDataOk() (*V0UserPlanDataModel, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *V0UserPlanRespModel) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given V0UserPlanDataModel and assigns it to the Data field.
func (o *V0UserPlanRespModel) SetData(v V0UserPlanDataModel) {
	o.Data = &v
}

func (o V0UserPlanRespModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0UserPlanRespModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableV0UserPlanRespModel struct {
	value *V0UserPlanRespModel
	isSet bool
}

func (v NullableV0UserPlanRespModel) Get() *V0UserPlanRespModel {
	return v.value
}

func (v *NullableV0UserPlanRespModel) Set(val *V0UserPlanRespModel) {
	v.value = val
	v.isSet = true
}

func (v NullableV0UserPlanRespModel) IsSet() bool {
	return v.isSet
}

func (v *NullableV0UserPlanRespModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0UserPlanRespModel(val *V0UserPlanRespModel) *NullableV0UserPlanRespModel {
	return &NullableV0UserPlanRespModel{value: val, isSet: true}
}

func (v NullableV0UserPlanRespModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0UserPlanRespModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


