/*
Bitrise API

Official REST API for Bitrise.io

API version: 0.1
Contact: letsconnect@bitrise.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V0TestDeviceListResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0TestDeviceListResponseModel{}

// V0TestDeviceListResponseModel struct for V0TestDeviceListResponseModel
type V0TestDeviceListResponseModel struct {
	Data []V0TestDeviceResponseItemModel `json:"data,omitempty"`
}

// NewV0TestDeviceListResponseModel instantiates a new V0TestDeviceListResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0TestDeviceListResponseModel() *V0TestDeviceListResponseModel {
	this := V0TestDeviceListResponseModel{}
	return &this
}

// NewV0TestDeviceListResponseModelWithDefaults instantiates a new V0TestDeviceListResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0TestDeviceListResponseModelWithDefaults() *V0TestDeviceListResponseModel {
	this := V0TestDeviceListResponseModel{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *V0TestDeviceListResponseModel) GetData() []V0TestDeviceResponseItemModel {
	if o == nil || IsNil(o.Data) {
		var ret []V0TestDeviceResponseItemModel
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0TestDeviceListResponseModel) GetDataOk() ([]V0TestDeviceResponseItemModel, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *V0TestDeviceListResponseModel) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []V0TestDeviceResponseItemModel and assigns it to the Data field.
func (o *V0TestDeviceListResponseModel) SetData(v []V0TestDeviceResponseItemModel) {
	o.Data = v
}

func (o V0TestDeviceListResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0TestDeviceListResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableV0TestDeviceListResponseModel struct {
	value *V0TestDeviceListResponseModel
	isSet bool
}

func (v NullableV0TestDeviceListResponseModel) Get() *V0TestDeviceListResponseModel {
	return v.value
}

func (v *NullableV0TestDeviceListResponseModel) Set(val *V0TestDeviceListResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableV0TestDeviceListResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableV0TestDeviceListResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0TestDeviceListResponseModel(val *V0TestDeviceListResponseModel) *NullableV0TestDeviceListResponseModel {
	return &NullableV0TestDeviceListResponseModel{value: val, isSet: true}
}

func (v NullableV0TestDeviceListResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0TestDeviceListResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


