/*
Bitrise API

Official REST API for Bitrise.io

API version: 0.1
Contact: letsconnect@bitrise.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V0ProvisionProfileListResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0ProvisionProfileListResponseModel{}

// V0ProvisionProfileListResponseModel struct for V0ProvisionProfileListResponseModel
type V0ProvisionProfileListResponseModel struct {
	Data []V0ProvisionProfileResponseItemModel `json:"data,omitempty"`
	Paging *V0PagingResponseModel `json:"paging,omitempty"`
}

// NewV0ProvisionProfileListResponseModel instantiates a new V0ProvisionProfileListResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0ProvisionProfileListResponseModel() *V0ProvisionProfileListResponseModel {
	this := V0ProvisionProfileListResponseModel{}
	return &this
}

// NewV0ProvisionProfileListResponseModelWithDefaults instantiates a new V0ProvisionProfileListResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0ProvisionProfileListResponseModelWithDefaults() *V0ProvisionProfileListResponseModel {
	this := V0ProvisionProfileListResponseModel{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *V0ProvisionProfileListResponseModel) GetData() []V0ProvisionProfileResponseItemModel {
	if o == nil || IsNil(o.Data) {
		var ret []V0ProvisionProfileResponseItemModel
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0ProvisionProfileListResponseModel) GetDataOk() ([]V0ProvisionProfileResponseItemModel, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *V0ProvisionProfileListResponseModel) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []V0ProvisionProfileResponseItemModel and assigns it to the Data field.
func (o *V0ProvisionProfileListResponseModel) SetData(v []V0ProvisionProfileResponseItemModel) {
	o.Data = v
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *V0ProvisionProfileListResponseModel) GetPaging() V0PagingResponseModel {
	if o == nil || IsNil(o.Paging) {
		var ret V0PagingResponseModel
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0ProvisionProfileListResponseModel) GetPagingOk() (*V0PagingResponseModel, bool) {
	if o == nil || IsNil(o.Paging) {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *V0ProvisionProfileListResponseModel) HasPaging() bool {
	if o != nil && !IsNil(o.Paging) {
		return true
	}

	return false
}

// SetPaging gets a reference to the given V0PagingResponseModel and assigns it to the Paging field.
func (o *V0ProvisionProfileListResponseModel) SetPaging(v V0PagingResponseModel) {
	o.Paging = &v
}

func (o V0ProvisionProfileListResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0ProvisionProfileListResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Paging) {
		toSerialize["paging"] = o.Paging
	}
	return toSerialize, nil
}

type NullableV0ProvisionProfileListResponseModel struct {
	value *V0ProvisionProfileListResponseModel
	isSet bool
}

func (v NullableV0ProvisionProfileListResponseModel) Get() *V0ProvisionProfileListResponseModel {
	return v.value
}

func (v *NullableV0ProvisionProfileListResponseModel) Set(val *V0ProvisionProfileListResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableV0ProvisionProfileListResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableV0ProvisionProfileListResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0ProvisionProfileListResponseModel(val *V0ProvisionProfileListResponseModel) *NullableV0ProvisionProfileListResponseModel {
	return &NullableV0ProvisionProfileListResponseModel{value: val, isSet: true}
}

func (v NullableV0ProvisionProfileListResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0ProvisionProfileListResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


