/*
Bitrise API

Official REST API for Bitrise.io

API version: 0.1
Contact: letsconnect@bitrise.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V0AppWebhookResponseItemModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0AppWebhookResponseItemModel{}

// V0AppWebhookResponseItemModel struct for V0AppWebhookResponseItemModel
type V0AppWebhookResponseItemModel struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Events []string `json:"events,omitempty"`
	Headers []int32 `json:"headers,omitempty"`
	RegisteredByAddon *bool `json:"registered_by_addon,omitempty"`
	Slug *string `json:"slug,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewV0AppWebhookResponseItemModel instantiates a new V0AppWebhookResponseItemModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0AppWebhookResponseItemModel() *V0AppWebhookResponseItemModel {
	this := V0AppWebhookResponseItemModel{}
	return &this
}

// NewV0AppWebhookResponseItemModelWithDefaults instantiates a new V0AppWebhookResponseItemModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0AppWebhookResponseItemModelWithDefaults() *V0AppWebhookResponseItemModel {
	this := V0AppWebhookResponseItemModel{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *V0AppWebhookResponseItemModel) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppWebhookResponseItemModel) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *V0AppWebhookResponseItemModel) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *V0AppWebhookResponseItemModel) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *V0AppWebhookResponseItemModel) GetEvents() []string {
	if o == nil || IsNil(o.Events) {
		var ret []string
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppWebhookResponseItemModel) GetEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *V0AppWebhookResponseItemModel) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []string and assigns it to the Events field.
func (o *V0AppWebhookResponseItemModel) SetEvents(v []string) {
	o.Events = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *V0AppWebhookResponseItemModel) GetHeaders() []int32 {
	if o == nil || IsNil(o.Headers) {
		var ret []int32
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppWebhookResponseItemModel) GetHeadersOk() ([]int32, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *V0AppWebhookResponseItemModel) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []int32 and assigns it to the Headers field.
func (o *V0AppWebhookResponseItemModel) SetHeaders(v []int32) {
	o.Headers = v
}

// GetRegisteredByAddon returns the RegisteredByAddon field value if set, zero value otherwise.
func (o *V0AppWebhookResponseItemModel) GetRegisteredByAddon() bool {
	if o == nil || IsNil(o.RegisteredByAddon) {
		var ret bool
		return ret
	}
	return *o.RegisteredByAddon
}

// GetRegisteredByAddonOk returns a tuple with the RegisteredByAddon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppWebhookResponseItemModel) GetRegisteredByAddonOk() (*bool, bool) {
	if o == nil || IsNil(o.RegisteredByAddon) {
		return nil, false
	}
	return o.RegisteredByAddon, true
}

// HasRegisteredByAddon returns a boolean if a field has been set.
func (o *V0AppWebhookResponseItemModel) HasRegisteredByAddon() bool {
	if o != nil && !IsNil(o.RegisteredByAddon) {
		return true
	}

	return false
}

// SetRegisteredByAddon gets a reference to the given bool and assigns it to the RegisteredByAddon field.
func (o *V0AppWebhookResponseItemModel) SetRegisteredByAddon(v bool) {
	o.RegisteredByAddon = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *V0AppWebhookResponseItemModel) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppWebhookResponseItemModel) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *V0AppWebhookResponseItemModel) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *V0AppWebhookResponseItemModel) SetSlug(v string) {
	o.Slug = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *V0AppWebhookResponseItemModel) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppWebhookResponseItemModel) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *V0AppWebhookResponseItemModel) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *V0AppWebhookResponseItemModel) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *V0AppWebhookResponseItemModel) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppWebhookResponseItemModel) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *V0AppWebhookResponseItemModel) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *V0AppWebhookResponseItemModel) SetUrl(v string) {
	o.Url = &v
}

func (o V0AppWebhookResponseItemModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0AppWebhookResponseItemModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.RegisteredByAddon) {
		toSerialize["registered_by_addon"] = o.RegisteredByAddon
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableV0AppWebhookResponseItemModel struct {
	value *V0AppWebhookResponseItemModel
	isSet bool
}

func (v NullableV0AppWebhookResponseItemModel) Get() *V0AppWebhookResponseItemModel {
	return v.value
}

func (v *NullableV0AppWebhookResponseItemModel) Set(val *V0AppWebhookResponseItemModel) {
	v.value = val
	v.isSet = true
}

func (v NullableV0AppWebhookResponseItemModel) IsSet() bool {
	return v.isSet
}

func (v *NullableV0AppWebhookResponseItemModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0AppWebhookResponseItemModel(val *V0AppWebhookResponseItemModel) *NullableV0AppWebhookResponseItemModel {
	return &NullableV0AppWebhookResponseItemModel{value: val, isSet: true}
}

func (v NullableV0AppWebhookResponseItemModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0AppWebhookResponseItemModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


