/*
Bitrise API

Official REST API for Bitrise.io

API version: 0.1
Contact: letsconnect@bitrise.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V0AppResponseItemModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0AppResponseItemModel{}

// V0AppResponseItemModel struct for V0AppResponseItemModel
type V0AppResponseItemModel struct {
	AvatarUrl *NullsString `json:"avatar_url,omitempty"`
	IsDisabled *bool `json:"is_disabled,omitempty"`
	IsGithubChecksEnabled *bool `json:"is_github_checks_enabled,omitempty"`
	IsPublic *bool `json:"is_public,omitempty"`
	Owner *V0OwnerAccountResponseModel `json:"owner,omitempty"`
	ProjectType *NullsString `json:"project_type,omitempty"`
	Provider *NullsString `json:"provider,omitempty"`
	RepoOwner *NullsString `json:"repo_owner,omitempty"`
	RepoSlug *NullsString `json:"repo_slug,omitempty"`
	RepoUrl *NullsString `json:"repo_url,omitempty"`
	Slug *string `json:"slug,omitempty"`
	Status *int32 `json:"status,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewV0AppResponseItemModel instantiates a new V0AppResponseItemModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0AppResponseItemModel() *V0AppResponseItemModel {
	this := V0AppResponseItemModel{}
	return &this
}

// NewV0AppResponseItemModelWithDefaults instantiates a new V0AppResponseItemModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0AppResponseItemModelWithDefaults() *V0AppResponseItemModel {
	this := V0AppResponseItemModel{}
	return &this
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetAvatarUrl() NullsString {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret NullsString
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetAvatarUrlOk() (*NullsString, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given NullsString and assigns it to the AvatarUrl field.
func (o *V0AppResponseItemModel) SetAvatarUrl(v NullsString) {
	o.AvatarUrl = &v
}

// GetIsDisabled returns the IsDisabled field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetIsDisabled() bool {
	if o == nil || IsNil(o.IsDisabled) {
		var ret bool
		return ret
	}
	return *o.IsDisabled
}

// GetIsDisabledOk returns a tuple with the IsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetIsDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDisabled) {
		return nil, false
	}
	return o.IsDisabled, true
}

// HasIsDisabled returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasIsDisabled() bool {
	if o != nil && !IsNil(o.IsDisabled) {
		return true
	}

	return false
}

// SetIsDisabled gets a reference to the given bool and assigns it to the IsDisabled field.
func (o *V0AppResponseItemModel) SetIsDisabled(v bool) {
	o.IsDisabled = &v
}

// GetIsGithubChecksEnabled returns the IsGithubChecksEnabled field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetIsGithubChecksEnabled() bool {
	if o == nil || IsNil(o.IsGithubChecksEnabled) {
		var ret bool
		return ret
	}
	return *o.IsGithubChecksEnabled
}

// GetIsGithubChecksEnabledOk returns a tuple with the IsGithubChecksEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetIsGithubChecksEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsGithubChecksEnabled) {
		return nil, false
	}
	return o.IsGithubChecksEnabled, true
}

// HasIsGithubChecksEnabled returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasIsGithubChecksEnabled() bool {
	if o != nil && !IsNil(o.IsGithubChecksEnabled) {
		return true
	}

	return false
}

// SetIsGithubChecksEnabled gets a reference to the given bool and assigns it to the IsGithubChecksEnabled field.
func (o *V0AppResponseItemModel) SetIsGithubChecksEnabled(v bool) {
	o.IsGithubChecksEnabled = &v
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetIsPublic() bool {
	if o == nil || IsNil(o.IsPublic) {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetIsPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublic) {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasIsPublic() bool {
	if o != nil && !IsNil(o.IsPublic) {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *V0AppResponseItemModel) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetOwner() V0OwnerAccountResponseModel {
	if o == nil || IsNil(o.Owner) {
		var ret V0OwnerAccountResponseModel
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetOwnerOk() (*V0OwnerAccountResponseModel, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given V0OwnerAccountResponseModel and assigns it to the Owner field.
func (o *V0AppResponseItemModel) SetOwner(v V0OwnerAccountResponseModel) {
	o.Owner = &v
}

// GetProjectType returns the ProjectType field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetProjectType() NullsString {
	if o == nil || IsNil(o.ProjectType) {
		var ret NullsString
		return ret
	}
	return *o.ProjectType
}

// GetProjectTypeOk returns a tuple with the ProjectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetProjectTypeOk() (*NullsString, bool) {
	if o == nil || IsNil(o.ProjectType) {
		return nil, false
	}
	return o.ProjectType, true
}

// HasProjectType returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasProjectType() bool {
	if o != nil && !IsNil(o.ProjectType) {
		return true
	}

	return false
}

// SetProjectType gets a reference to the given NullsString and assigns it to the ProjectType field.
func (o *V0AppResponseItemModel) SetProjectType(v NullsString) {
	o.ProjectType = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetProvider() NullsString {
	if o == nil || IsNil(o.Provider) {
		var ret NullsString
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetProviderOk() (*NullsString, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullsString and assigns it to the Provider field.
func (o *V0AppResponseItemModel) SetProvider(v NullsString) {
	o.Provider = &v
}

// GetRepoOwner returns the RepoOwner field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetRepoOwner() NullsString {
	if o == nil || IsNil(o.RepoOwner) {
		var ret NullsString
		return ret
	}
	return *o.RepoOwner
}

// GetRepoOwnerOk returns a tuple with the RepoOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetRepoOwnerOk() (*NullsString, bool) {
	if o == nil || IsNil(o.RepoOwner) {
		return nil, false
	}
	return o.RepoOwner, true
}

// HasRepoOwner returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasRepoOwner() bool {
	if o != nil && !IsNil(o.RepoOwner) {
		return true
	}

	return false
}

// SetRepoOwner gets a reference to the given NullsString and assigns it to the RepoOwner field.
func (o *V0AppResponseItemModel) SetRepoOwner(v NullsString) {
	o.RepoOwner = &v
}

// GetRepoSlug returns the RepoSlug field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetRepoSlug() NullsString {
	if o == nil || IsNil(o.RepoSlug) {
		var ret NullsString
		return ret
	}
	return *o.RepoSlug
}

// GetRepoSlugOk returns a tuple with the RepoSlug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetRepoSlugOk() (*NullsString, bool) {
	if o == nil || IsNil(o.RepoSlug) {
		return nil, false
	}
	return o.RepoSlug, true
}

// HasRepoSlug returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasRepoSlug() bool {
	if o != nil && !IsNil(o.RepoSlug) {
		return true
	}

	return false
}

// SetRepoSlug gets a reference to the given NullsString and assigns it to the RepoSlug field.
func (o *V0AppResponseItemModel) SetRepoSlug(v NullsString) {
	o.RepoSlug = &v
}

// GetRepoUrl returns the RepoUrl field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetRepoUrl() NullsString {
	if o == nil || IsNil(o.RepoUrl) {
		var ret NullsString
		return ret
	}
	return *o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetRepoUrlOk() (*NullsString, bool) {
	if o == nil || IsNil(o.RepoUrl) {
		return nil, false
	}
	return o.RepoUrl, true
}

// HasRepoUrl returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasRepoUrl() bool {
	if o != nil && !IsNil(o.RepoUrl) {
		return true
	}

	return false
}

// SetRepoUrl gets a reference to the given NullsString and assigns it to the RepoUrl field.
func (o *V0AppResponseItemModel) SetRepoUrl(v NullsString) {
	o.RepoUrl = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *V0AppResponseItemModel) SetSlug(v string) {
	o.Slug = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *V0AppResponseItemModel) SetStatus(v int32) {
	o.Status = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *V0AppResponseItemModel) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0AppResponseItemModel) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *V0AppResponseItemModel) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *V0AppResponseItemModel) SetTitle(v string) {
	o.Title = &v
}

func (o V0AppResponseItemModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0AppResponseItemModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	if !IsNil(o.IsDisabled) {
		toSerialize["is_disabled"] = o.IsDisabled
	}
	if !IsNil(o.IsGithubChecksEnabled) {
		toSerialize["is_github_checks_enabled"] = o.IsGithubChecksEnabled
	}
	if !IsNil(o.IsPublic) {
		toSerialize["is_public"] = o.IsPublic
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.ProjectType) {
		toSerialize["project_type"] = o.ProjectType
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.RepoOwner) {
		toSerialize["repo_owner"] = o.RepoOwner
	}
	if !IsNil(o.RepoSlug) {
		toSerialize["repo_slug"] = o.RepoSlug
	}
	if !IsNil(o.RepoUrl) {
		toSerialize["repo_url"] = o.RepoUrl
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

type NullableV0AppResponseItemModel struct {
	value *V0AppResponseItemModel
	isSet bool
}

func (v NullableV0AppResponseItemModel) Get() *V0AppResponseItemModel {
	return v.value
}

func (v *NullableV0AppResponseItemModel) Set(val *V0AppResponseItemModel) {
	v.value = val
	v.isSet = true
}

func (v NullableV0AppResponseItemModel) IsSet() bool {
	return v.isSet
}

func (v *NullableV0AppResponseItemModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0AppResponseItemModel(val *V0AppResponseItemModel) *NullableV0AppResponseItemModel {
	return &NullableV0AppResponseItemModel{value: val, isSet: true}
}

func (v NullableV0AppResponseItemModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0AppResponseItemModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


