/*
Bitrise API

Official REST API for Bitrise.io

API version: 0.1
Contact: letsconnect@bitrise.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V0ArchivedBuildListResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0ArchivedBuildListResponseModel{}

// V0ArchivedBuildListResponseModel struct for V0ArchivedBuildListResponseModel
type V0ArchivedBuildListResponseModel struct {
	Data []V0ArchivedBuildResponseItemModel `json:"data,omitempty"`
	Paging *V0PagingResponseModel `json:"paging,omitempty"`
}

// NewV0ArchivedBuildListResponseModel instantiates a new V0ArchivedBuildListResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0ArchivedBuildListResponseModel() *V0ArchivedBuildListResponseModel {
	this := V0ArchivedBuildListResponseModel{}
	return &this
}

// NewV0ArchivedBuildListResponseModelWithDefaults instantiates a new V0ArchivedBuildListResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0ArchivedBuildListResponseModelWithDefaults() *V0ArchivedBuildListResponseModel {
	this := V0ArchivedBuildListResponseModel{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *V0ArchivedBuildListResponseModel) GetData() []V0ArchivedBuildResponseItemModel {
	if o == nil || IsNil(o.Data) {
		var ret []V0ArchivedBuildResponseItemModel
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0ArchivedBuildListResponseModel) GetDataOk() ([]V0ArchivedBuildResponseItemModel, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *V0ArchivedBuildListResponseModel) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []V0ArchivedBuildResponseItemModel and assigns it to the Data field.
func (o *V0ArchivedBuildListResponseModel) SetData(v []V0ArchivedBuildResponseItemModel) {
	o.Data = v
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *V0ArchivedBuildListResponseModel) GetPaging() V0PagingResponseModel {
	if o == nil || IsNil(o.Paging) {
		var ret V0PagingResponseModel
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0ArchivedBuildListResponseModel) GetPagingOk() (*V0PagingResponseModel, bool) {
	if o == nil || IsNil(o.Paging) {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *V0ArchivedBuildListResponseModel) HasPaging() bool {
	if o != nil && !IsNil(o.Paging) {
		return true
	}

	return false
}

// SetPaging gets a reference to the given V0PagingResponseModel and assigns it to the Paging field.
func (o *V0ArchivedBuildListResponseModel) SetPaging(v V0PagingResponseModel) {
	o.Paging = &v
}

func (o V0ArchivedBuildListResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0ArchivedBuildListResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Paging) {
		toSerialize["paging"] = o.Paging
	}
	return toSerialize, nil
}

type NullableV0ArchivedBuildListResponseModel struct {
	value *V0ArchivedBuildListResponseModel
	isSet bool
}

func (v NullableV0ArchivedBuildListResponseModel) Get() *V0ArchivedBuildListResponseModel {
	return v.value
}

func (v *NullableV0ArchivedBuildListResponseModel) Set(val *V0ArchivedBuildListResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableV0ArchivedBuildListResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableV0ArchivedBuildListResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0ArchivedBuildListResponseModel(val *V0ArchivedBuildListResponseModel) *NullableV0ArchivedBuildListResponseModel {
	return &NullableV0ArchivedBuildListResponseModel{value: val, isSet: true}
}

func (v NullableV0ArchivedBuildListResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0ArchivedBuildListResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


