# This version of the CLA Assistant uses a GitHub action and local
# storage of the signatures.
# https://github.com/cla-assistant/github-action/

name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
        # Alpha Release
        uses: cla-assistant/github-action@v1.3.0-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-To-cladocument: 'https://github.com/Staffbase/template-oss-repository/blob/master/CLA.md'
          # branch should not be protected
          branch: 'signatures'
          # no whitelist currently
          whitelist: cstaud,staust
          empty-commit-flag: false
          blockchain-storage-flag: false